source 'https://github.com/CocoaPods/Specs.git'

target 'Segment-Optimizely_Example', :exclusive => true do
  pod "Segment-Optimizely", :path => "../"
end

target 'Segment-Optimizely_Tests', :exclusive => true do
  pod "Segment-Optimizely", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
